### ISSUE TITLE
3.9 - severe bug - can't edit course

### ISSUE THREAD

**Issue by aspark21** [blackboard-open-source/moodle-tool_ally#45]
Moodle: 3.9.1
Ally plugins: latest master as of 29/07/20

Edit dropdowns for editing activities and course section (when in editing mode as a teacher) fail to load 

Following errors in console:
<img width="966" alt="Screenshot 2020-07-29 at 22 49 05" src="https://user-images.githubusercontent.com/4015496/88857435-2fa53800-d1ee-11ea-892a-68cda5a1767c.png">
http://requirejs.org/docs/errors.html#mismatch

Tested with different themes. Tracks back to tool_ally

**Comment by aspark21** [comment]
Also affects 3.7.7.
Could be a clash between Ally & a new plugin as I can't find any recent changes to attribute it to.

**Comment by dvdcastro** [comment]
Hi @aspark21 Can you enable debug mode to see if we can pinpoint the location?
```php
$CFG->debug = E_ALL | E_STRICT; // DEBUG_DEVELOPER
$CFG->debugdisplay = '1';
$CFG->perfdebug = '15';
$CFG->debugpageinfo = '1';
$CFG->cachejs = '0';
```

**Comment by cybernotic** [comment]
Hi, Debug mode was already enabled, the issue appears as soon as you login, clicking on the profile icon has no effect, no dropdown menu appears and that's when I'm logged on as a site admin. With blackbord ally not installed no issue occurs.
Are there steps you can instruct me to carry out so that I can gather more information for you?

**Comment by aspark21** [comment]
Not directly an Ally issue after all
